### ISSUE TITLE
Project death?

### ISSUE THREAD

**Issue by Krawei** [WizzardMaker/OpenATDeluxe#1]
Dear WizzardMaker,

it seems that there is no work in progress here. Is your project death or will there be a release soon?

Kind Regards,

Krawei

**Comment by WizzardMaker** [comment]
It's not really dead, I wrote some code here and there, but I can't find the time to fully commit to it at the moment. There will be a lot of downtime for me in the near future where I will be focusing on this project though.

This project is rather far from a real release. The engine is missing some core features like sounds or animations and the integration with C# has to be improved as well.

I am always watching this page and will gladly help others.
An update will come soon though with some additions to the C++ engine for better C# compatibility.

I hope that answers your question

**Comment by Serphentas** [comment]
There a thread on [Steam forums](https://steamcommunity.com/app/331920/discussions/0/1815422173030798091/) hence the regain in interest. I do have time to spare for this project but I'm not sure C# is fit for the easiest and most painless multi-platform port.

Given that the game is not very resource hungry, I think other languages could benefit us.

**Comment by WizzardMaker** [comment]
It really depends. C# is very multi platform when used with mono instead of .Net

The base of the game engine is that what's of my concern. Creating an engine just for the game has benefits but there is a lot of overhead and I can't really see the reason now for reinventing the wheel.

There are a lot of options
Going the pre built engine route with
-MonoGame, Godot etc

Going the self made route with
-SDL or the like

Other Programming languages are kind of problematic, languages like Lua, or maybe Rust aren't too well documented and I don't really know the ins and outs of those. 

SDL Mono C# is supported on all major platforms like Windows, Mac, Linux

**Comment by Serphentas** [comment]
From a C++ perspective Godot is the safest bet, and surely rolling a custom engine with that language is a PITA.

For other languages, I was thinking more about Python or Java. Rust isn't suitable for games right now even though it's an interesting lang.

Thoughts ?

**Comment by WizzardMaker** [comment]
Godot is a nice engine and got a few updates for 2D.
Python is a bit too restrictive in my opinion in regards to graphics
Java has kind of a bad stigma with video games (and I don't really like it personally)

In practice all engines are possible, we would only need to? port the file extraction function from C++

The game logic is also half open source with the gog version.
I would suggest trying something like godot in a new branch. I can open one up and add simple er

**Comment by Serphentas** [comment]
I tried reading the GFXlib files but it's a bit too cryptic to me as is. I could hardly make a pseudocode out of it just to understand the basic working principle.

Could you perhaps clean it up a bit or add some doc/notes ? As for the new branch, I'd gladly take a contributor access.

**Comment by WizzardMaker** [comment]
Yeah, I wanted to refractor a lot of it, most of it is of disassembly of the original code, with tweaks for SDL.

I will open the branch as soon as I can, with a nice readme too. Time to refresh the old one. Closing now the issue too.

**Comment by Serphentas** [comment]
Sweet, thanks !
