### ISSUE TITLE
programming language decision

### ISSUE THREAD

**Issue by WizzardMaker** [WizzardMaker/OpenATDeluxe#2]
We have to decide a language for the project when using Godot.
I don't want a mumbo jumbo of 4 different languages having to work together.

We have to decide between:
**C#** - not yet 100% production ready in Godot, but feature complete and has all the benefits of C# like strong typing, LINQ, easy understanding

**C++** - fully supported by godot, Godot enforced overhead for editor variables, standard functions etc. Not as easy to get into learning curve wise for other contributors

**GDScript** - 100% supported by godot. Unknown language for me and maybe others

**Comment by Serphentas** [comment]
C# seems to be supported, at least in the 7.x branch. I think it's safer because you can easily fall into a pointer & memory mess with C++, even though I know the latter better. Since the game is going to be so light anyway, perhaps it's worth giving GDScript a shot too. My two cents.

**Comment by WizzardMaker** [comment]
I know C++ well, but it's a whole new problem when you use it for games. You can run into some problems later on.

C# would enable support for IntelliSense in Visual Studio Code and also gives the possibilities to use platform independent external libraries, or easier modding support (In theory, we should be able to just load other C# assemblies from a /,mod folder later on).

I read a bit about people switching from GDScript to C# and they agreed that C# has many advantages against GDScript

**Comment by Serphentas** [comment]
I'd say let's roll with C#. We can use GDScript bits of code if needed anyway.

**Comment by WizzardMaker** [comment]
Done

Updating the Readme now and porting the image extraction code to C# will be done in around 50 minutes or so

**Comment by Serphentas** [comment]
Tiptop 👍🏻
