### ISSUE TITLE
Add some screenshots in the README

### ISSUE THREAD

**Issue by neuromancer** [WizzardMaker/OpenATDeluxe#3]
I think people will be more interested in testing this re-implementation and maybe collaborate with some code if you show the current state of this port. Even early screenshots are fine!

**Comment by WizzardMaker** [comment]
Sure can do!
Stay tuned

**Comment by Serphentas** [comment]
I'm currently playing around with the new code too so yeah, soon good stuff !

**Comment by WizzardMaker** [comment]
Nice to hear!
You are free to use the project board too if you want. Will prevent duplicate work if you are planning something :)
